### PR TITLE
Added support for the CYW43455 (Type 1MW) WiFi chip on a new SOM vari…

### PR DESCRIPTION
**Pull request by sposelenov-emcraft**
…ant.

This change will support both WiFi variants that are installed to Emcraft LPDDR4 SOM

### CODE REVIEW

**Comment by PetervdPerk-NXP** [comment]
Hi @sposelenov,
Looking at the patch it seems to be changing the existing device tree, does this break the config for old SOM variant?

**Comment by sposelenov-emcraft** [comment]
Hello Peter,

This change is compatible with the old SOM variant.

Regards,
Vlad

**Comment by PetervdPerk-NXP** [comment]
LGTM, could you make a PR for the master branch as well?

**Comment by sposelenov-emcraft** [comment]
Hi, cherry-picked to master, verified it builds OK.
PR https://github.com/NXPmicro/meta-nxp-hovergames/pull/18

Regards,
Sergei

**Pull request merged**
