### PR TITLE
HDMI, Coral cam and TCPC related fixes

### PR DESCRIPTION
**Pull request by ayurtsev**
A set of patches from the Emcraft 8m mini kernel tree.

### CODE REVIEW

**Comment by thochstein** [comment]
Hi Alex, sorry but your changes are now in conflict because I pushed a couple of changes for Rogerio Silva. Can you have a look?

**Comment by thochstein** [comment]
So patches 3, 4, and 5 were already in, I guess introduced by Rogerio. I took care of the other patches.

**Comment by thochstein** [comment]
Hi Alex, are you using our 5.4.24 release now? I didn't notice a problem with the patches, but Rogerio thought you might still be on 5.4.3?

**Comment by ayurtsev** [comment]
Hi Tom, we have a customized meta layer on 5.4.3, which we used initially for our 8m mini kits. And most of the work was done there. For NavQ kits we switched to using the NXP meta-nxp-hovergames/5.4.24.

**Pull request closed without merging**
